### ISSUE TITLE
esdoc2-publish-html-plugin error

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#10]
I just updated my project to use esdoc2 instead of esdoc.

Sadly I get this error:

```shell
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Cannot find module 'esdoc2-publish-html-plugin/out/src/Builder/DocBuilder'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/greada/Documents/workspace/s2/dekk/node_modules/esdoc2-react-plugin/src/Plugin.js:4:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' } } reason: { Error: Cannot find module 'esdoc2-publish-html-plugin/out/src/Builder/DocBuilder'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/greada/Documents/workspace/s2/dekk/node_modules/esdoc2-react-plugin/src/Plugin.js:4:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by grount** [comment]
I have the same error.
Tried installing esdoc2-publish-html-plugin in npm but still no success.

**Comment by chrisdel101** [comment]
I also have this issue.. Esdocs regular would not generate docs so I tried Esdocs2 but cannot run it.

**Comment by pixelass** [comment]
I looked into the issue:

The publish-html plugin exposes an `out` folder but it has not been generated for releases.

This might also be related to the original repo defining `out` inside the gitignore.

I think a local `.npmigore` should be provided to ensure all files are valid for exposure.

**.npmignore**

```
src
!out/src
```

```json
{
 "files": [
    "out/src",
    "README.md"
  ],
  "main": "out/src/Plugin.js"
}

```

<img width="301" alt="screen shot 2018-03-12 at 12 35 44" src="https://user-images.githubusercontent.com/1148334/37281715-40d4e3c8-25f2-11e8-9148-00723a185f7f.png">

I will test this and prepare a PR as soon as this has been confirmed.

**Comment by holmrenser** [comment]
This is currently preventing me from switching to esdoc2. Any idea on when/how this will be fixed?

**Comment by MattMcFarland** [comment]
With yarn build chain working properly, we now have some failing unit tests but it seems to be working.

**Comment by pixelass** [comment]
haven't found the time to test this. But I think it should work now.

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.

**Comment by ajmeese7** [comment]
I would like to see this re-opened!
