### ISSUE TITLE
impossible build chain

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#14]
The build chain is impossible to resolve.

1. preinstall runs lerna bootstrap.
2. local scripts might require dependencies (eg. babel)
3. dependencies are never installed.

There are too many references to compiled versions before they exist. This currently prevents me from fixing several issues.

#10 #12

**Comment by pixelass** [comment]
```
✔ ~/Documents/workspace/github/esdoc2-plugins [bug/yarn-workspaces L|✔] 
12:57 $ lerna bootstrap --npm-client=yarn
lerna info version 2.9.0
lerna info Bootstrapping 24 packages

```

=> MANUAL ABORT after ~ 4 minutes

```
✘-INT ~/Documents/workspace/github/esdoc2-plugins [bug/yarn-workspaces L|✚ 1] 
12:59 $ lerna run build --npm-client=yarn
lerna info version 2.9.0
lerna ERR! build Errored while running script in 'esdoc2-publish-html-plugin'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/.babelrc" at 0, attempted to resolve relative to "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin"
lerna ERR!     at /Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at Function.normalisePlugins (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
lerna ERR!     at OptionManager.mergeOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
lerna ERR!     at OptionManager.init (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
lerna ERR!     at File.initOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)
lerna ERR!     at new File (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)
lerna ERR!     at Pipeline.transform (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
lerna ERR!     at transform (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:50:22)
lerna ERR!     at Object.compile (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:59:12)
lerna ERR! error An unexpected error occurred: "Command failed.
lerna ERR! Exit code: 1
lerna ERR! Command: sh
lerna ERR! Arguments: -c rm -rf ./out/src && babel --out-dir out/src --ignore 'Builder/template' src && cp -a src/Builder/template out/src/Builder/
lerna ERR! Directory: /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin
lerna ERR! Output:
lerna ERR! ".
lerna ERR! yarn run v1.5.1
lerna ERR! $ rm -rf ./out/src && babel --out-dir out/src --ignore 'Builder/template' src && cp -a src/Builder/template out/src/Builder/
lerna ERR! info If you think this is a bug, please open a bug report with the information provided in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/yarn-error.log".
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/greada/.config/yarn/global/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: yarn run build
ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/.babelrc" at 0, attempted to resolve relative to "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin"
    at /Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:59:12)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c rm -rf ./out/src && babel --out-dir out/src --ignore 'Builder/template' src && cp -a src/Builder/template out/src/Builder/
Directory: /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin
Output:
".
yarn run v1.5.1
$ rm -rf ./out/src && babel --out-dir out/src --ignore 'Builder/template' src && cp -a src/Builder/template out/src/Builder/
info If you think this is a bug, please open a bug report with the information provided in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/greada/.config/yarn/global/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: 'yarn run v1.5.1\n$ rm -rf ./out/src && babel --out-dir out/src --ignore \'Builder/template\' src && cp -a src/Builder/template out/src/Builder/\ninfo If you think this is a bug, please open a bug report with the information provided in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'ReferenceError: Unknown plugin "transform-es2015-modules-commonjs" specified in "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/.babelrc" at 0, attempted to resolve relative to "/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin"\n    at /Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17\n    at Array.map (<anonymous>)\n    at Function.normalisePlugins (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)\n    at OptionManager.mergeOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)\n    at OptionManager.init (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)\n    at File.initOptions (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:212:65)\n    at new File (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/file/index.js:135:24)\n    at Pipeline.transform (/Users/greada/.config/yarn/global/node_modules/babel-core/lib/transformation/pipeline.js:46:16)\n    at transform (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:50:22)\n    at Object.compile (/Users/greada/.config/yarn/global/node_modules/babel-cli/lib/babel/util.js:59:12)\nerror An unexpected error occurred: "Command failed.\nExit code: 1\nCommand: sh\nArguments: -c rm -rf ./out/src && babel --out-dir out/src --ignore \'Builder/template\' src && cp -a src/Builder/template out/src/Builder/\nDirectory: /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin\nOutput:\n".\n',
  failed: true,
  signal: null,
  cmd: 'yarn run build',
  timedOut: false,
  exitCode: 1 }

```

**Comment by MattMcFarland** [comment]
Thanks, I will look into this.

**Comment by holmrenser** [comment]
I think #16 fixes this. At least I am now able to run ```npm run bootstrap``` to execute lerna bootstrapping.
