### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by pixelass** [esdoc2/esdoc2-plugins#15]
I can't set up this repository:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/esdoc2/-/esdoc2-1.1.0.tgz: Request failed \"404 Not Found\"".
```

**Comment by pixelass** [comment]
#14 #10 #12

**Comment by MattMcFarland** [comment]
Sorry about this, and thanks so much for your contributions, I will give
you push access and will help.

**Comment by pixelass** [comment]
no worries. I finally found some free time ;)

**Comment by MattMcFarland** [comment]
Hey, I've added you as an owner, so you can now update all projects under esdoc2 freely.  I also encourage you to add yourself in the package.json files to you can use npm publish.

**Comment by MattMcFarland** [comment]
I have yarn working locally, is this issue still occurring?

**Comment by pixelass** [comment]
## Git log

```shell
19:29 $ git log
commit 276c7203b8e9bbb0beca49bbd909368f9f4de89b (HEAD -> master, origin/master, origin/HEAD)
Author: Matt McFarland <contact@mattmcfarland.com>
Date:   Thu Mar 22 14:08:22 2018 -0400

    v2.1.2


```

## Yarn

```
19:30 $ yarn
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/esdoc2/-/esdoc2-1.1.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/greada/Documents/workspace/github/esdoc2-plugins/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by pixelass** [comment]
## Lerna

```shell
19:30 $ lerna bootstrap
lerna info version 2.9.0
lerna info Bootstrapping 24 packages
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN deprecated to-markdown@3.0.4: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown
lerna ERR! npm ERR! code ETARGET
lerna ERR! npm ERR! notarget No matching version found for esdoc2-publish-html-plugin@^2.1.2
lerna ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
lerna ERR! npm ERR! notarget a package version that doesn't exist.
lerna ERR! npm ERR! notarget 
lerna ERR! npm ERR! notarget It was specified as a dependency of 'esdoc2-standard-plugin'
lerna ERR! npm ERR! notarget 
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/greada/.npm/_logs/2018-03-22T18_31_25_717Z-debug.log
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/greada/.config/yarn/global/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm install
npm WARN deprecated to-markdown@3.0.4: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown
npm ERR! code ETARGET
npm ERR! notarget No matching version found for esdoc2-publish-html-plugin@^2.1.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'esdoc2-standard-plugin'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greada/.npm/_logs/2018-03-22T18_31_25_717Z-debug.log

    at Promise.all.then.arr (/Users/greada/.config/yarn/global/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'npm WARN deprecated to-markdown@3.0.4: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown\nnpm ERR! code ETARGET\nnpm ERR! notarget No matching version found for esdoc2-publish-html-plugin@^2.1.2\nnpm ERR! notarget In most cases you or one of your dependencies are requesting\nnpm ERR! notarget a package version that doesn\'t exist.\nnpm ERR! notarget \nnpm ERR! notarget It was specified as a dependency of \'esdoc2-standard-plugin\'\nnpm ERR! notarget \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/greada/.npm/_logs/2018-03-22T18_31_25_717Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
```

**Comment by pixelass** [comment]
Looks like `2.0.1` is the latest published version of `esdoc2-publish-html-plugin`
(looking for 2.1.2 fails)

can you please run: 

```
npx rimraf **/node_modules
yarn ## or npm i
```

The package might be linked in your local node_modules

**Comment by MattMcFarland** [comment]
argh was on the wrong npm registry, i just published to the proper one.

**Comment by pixelass** [comment]
```shell
✔ ~/Documents/workspace/github 
20:18 $ git clone git@github.com:esdoc2/esdoc2-plugins.git
Cloning into 'esdoc2-plugins'...
remote: Counting objects: 2844, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 2844 (delta 22), reused 30 (delta 15), pack-reused 2801
Receiving objects: 100% (2844/2844), 755.28 KiB | 39.00 KiB/s, done.
Resolving deltas: 100% (1432/1432), done.
✔ ~/Documents/workspace/github 
20:18 $ cd esdoc2-plugins/
✔ ~/Documents/workspace/github/esdoc2-plugins [master|✔] 
20:18 $ yarn
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/esdoc2/-/esdoc2-1.1.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/greada/Documents/workspace/github/esdoc2-plugins/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✘-1 ~/Documents/workspace/github/esdoc2-plugins [master|✔] 
20:18 $ npm install
npm WARN deprecated to-markdown@3.0.4: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown
npm notice created a lockfile as package-lock.json. You should commit this file.
added 536 packages in 9.434s
✔ ~/Documents/workspace/github/esdoc2-plugins [master|…1] 
20:19 $ yarn bootstrap
yarn run v1.5.1
$ lerna bootstrap --npm-client=npm
lerna info version 2.9.0
lerna info Bootstrapping 24 packages
lerna info hoist Finished installing in root
lerna success Bootstrapped 24 packages
✨  Done in 3.45s.
✔ ~/Documents/workspace/github/esdoc2-plugins [master|…1] 
20:20 $ npm run test

> esdoc2-plugins@2.0.1 test /Users/greada/Documents/workspace/github/esdoc2-plugins
> lerna run test

lerna info version 2.9.0

> esdoc2-accessor-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-accessor-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-coverage-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-coverage-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-brand-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-brand-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-ecmascript-proposal-plugin@2.1.1 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-ecmascript-proposal-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

warning: could not parse the following code. if you want to use ECMAScript proposals, see https://esdoc2.org/manual/feature.html#ecmascript-proposal
/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-ecmascript-proposal-plugin/test/src/ExportExtensions.js
1| export * as ns from 'mod'
2| export v from "mod"
3| export vv, {x, y as w} from "mod"
4| export default from "mod"
== finish ==

> esdoc2-exclude-source-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-exclude-source-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-external-nodejs-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-external-nodejs-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-external-ecmascript-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-external-ecmascript-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-external-webapi-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-external-webapi-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-importpath-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-importpath-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-inject-script-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-inject-script-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-inject-style-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-inject-style-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-flow-type-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-flow-type-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

resolve: extends chain
resolve: necessary
resolve: ignore
resolve: link
resolve: markdown in description
resolve: test relation
== finish ==

> esdoc2-integrate-manual-plugin@2.1.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-integrate-manual-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==

> esdoc2-integrate-test-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-integrate-test-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

parse: /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-integrate-test-plugin/test/test/Test.js
== finish ==

> esdoc2-jsx-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-jsx-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==
lerna ERR! test Errored while running script in 'esdoc2-publish-html-plugin'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! module.js:549
lerna ERR!     throw err;
lerna ERR!     ^
lerna ERR! 
lerna ERR! Error: Cannot find module 'babel-register'
lerna ERR!     at Function.Module._resolveFilename (module.js:547:15)
lerna ERR!     at Function.Module._load (module.js:474:25)
lerna ERR!     at Module.require (module.js:596:17)
lerna ERR!     at require (internal/module.js:11:18)
lerna ERR!     at Object.<anonymous> (/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/test/init.js:1:63)
lerna ERR!     at Module._compile (module.js:652:30)
lerna ERR!     at Object.Module._extensions..js (module.js:663:10)
lerna ERR!     at Module.load (module.js:565:32)
lerna ERR!     at tryModuleLoad (module.js:505:12)
lerna ERR!     at Function.Module._load (module.js:497:3)
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! esdoc2-publish-html-plugin@2.1.2 test: `rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the esdoc2-publish-html-plugin@2.1.2 test script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/greada/.npm/_logs/2018-03-22T19_20_21_030Z-debug.log
lerna ERR! 
lerna ERR! > esdoc2-publish-html-plugin@2.1.2 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin
lerna ERR! > rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec
lerna ERR! 
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/greada/Documents/workspace/github/esdoc2-plugins/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.

> esdoc2-lint-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-lint-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

warning: signature mismatch: MyClass#method1 src/MyClass.js#4
4|   /**
5|    * this is method1.
6|    * @param {number} x
7|    */
8|   method1(p){}

warning: signature mismatch: MyClass#method2 src/MyClass.js#10
10|   /**
11|    * this is method2.
12|    * @param {number} x1
13|    * @param {number[]} x2
14|    * @param {Object} x3
15|    */
16|   method2(p1 = 10, p2 = [1,2,3], p3 = {foo:1, bar: 2}){}

warning: signature mismatch: MyClass#method3 src/MyClass.js#18
18|   /**
19|    * this is method3.
20|    * @param {number[]} x
21|    */
22|   method3(...p){}

warning: signature mismatch: MyClass#method4 src/MyClass.js#24
24|   /**
25|    * this is method4.
26|    * @param {Object} o
27|    */
28|   method4({p1, p2}, {p3, p4}){}

== finish ==

> esdoc2-react-plugin@2.0.0 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-react-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

resolve: extends chain
resolve: necessary
resolve: ignore
resolve: link
resolve: markdown in description
resolve: test relation
== finish ==

> esdoc2-publish-markdown-plugin@2.1.1 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-markdown-plugin
> rm -rf ./test/out && node ./test/init.js mocha --require $(find test/ -regex '.*.test.js$') -R spec

== finish ==
{ Error: Command failed: npm run test
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/test/init.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esdoc2-publish-html-plugin@2.1.2 test: `rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esdoc2-publish-html-plugin@2.1.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greada/.npm/_logs/2018-03-22T19_20_21_030Z-debug.log

> esdoc2-publish-html-plugin@2.1.2 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin
> rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec


    at Promise.all.then.arr (/Users/greada/Documents/workspace/github/esdoc2-plugins/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '\n> esdoc2-publish-html-plugin@2.1.2 test /Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin\n> rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec\n\n',
  stderr: 'module.js:549\n    throw err;\n    ^\n\nError: Cannot find module \'babel-register\'\n    at Function.Module._resolveFilename (module.js:547:15)\n    at Function.Module._load (module.js:474:25)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/greada/Documents/workspace/github/esdoc2-plugins/packages/esdoc2-publish-html-plugin/test/init.js:1:63)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! esdoc2-publish-html-plugin@2.1.2 test: `rm -rf ./test/fixture/out && node ./test/init.js && mocha -t 10000 --require ./node_modules/babel-register --recursive ./test/src -R spec`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the esdoc2-publish-html-plugin@2.1.2 test script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\nnpm WARN Local package.json exists, but node_modules missing, did you mean to install?\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/greada/.npm/_logs/2018-03-22T19_20_21_030Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run test',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esdoc2-plugins@2.0.1 test: `lerna run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esdoc2-plugins@2.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greada/.npm/_logs/2018-03-22T19_20_22_334Z-debug.log
```

**Comment by MattMcFarland** [comment]
I cant reproduce that problem, I think it might have to do with I used yarn to install everything instead of lerna bootstrap, I am going to try to reproduce.

**Comment by pixelass** [comment]
I fixed it ;)

wrong reference in yarn.lock. 

Sadly I still can't push ;(

**Comment by MattMcFarland** [comment]
I just pushed a new update, and it updated yarn.lock on top of yours. 

also, check this: https://github.com/esdoc2/esdoc2-plugins/invitations

you should have write access if you click that link
